version: "3.7"

services:

  postgres:
    image: in-sylva.postgres:latest
    container_name: in-sylva.postgres
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_MULTIPLE_DATABASES: insylva,keycloak
      POSTGRES_USER: insylva_admin_pg
      POSTGRES_PASSWORD: v2kGBDUaGjXK2VuPyf5R64VS
      POSTGRES_HOST: postgres
    ports:
      - 5432:5432
    networks:
      - insylva-net
    restart: unless-stopped
  
  keycloak:
    image: in-sylva.keycloak:latest
    container_name: in-sylva.keycloak
    environment:
      network.host: 0.0.0.0

      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_PORT: 5432
      DB_DATABASE: keycloak

      DB_USER: insylva_admin_pg
      DB_SCHEMA: public
      DB_PASSWORD: v2kGBDUaGjXK2VuPyf5R64VS

      KEYCLOAK_USER: insylva_admin
      KEYCLOAK_PASSWORD: v2kGBDUaGjXK2VuPyf5R64VS
      
      # KEYCLOAK_IMPORT: /home/realms/realm-export.json
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      # JDBC_PARAMS: useSSL=false
      # JGROUPS_DISCOVERY_PROTOCOL: JDBC_PING
      # JGROUPS_DISCOVERY_PROPERTIES: datasource_jndi_name=java:jboss/datasources/KeycloakDS,info_writer_sleep_time=500,initialize_sql="CREATE TABLE IF NOT EXISTS JGROUPSPING ( own_addr varchar(200) NOT NULL, cluster_name varchar(200) NOT NULL, created timestamp default current_timestamp, ping_data BYTEA, constraint PK_JGROUPSPING PRIMARY KEY (own_addr, cluster_name))"
    ports:
      - 7000:8080
    depends_on:
      - postgres
    networks:
      - insylva-net
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: aytac.ozkan@inra.fr
      PGADMIN_DEFAULT_PASSWORD: v2kGBDUaGjXK2VuPyf5R64VS
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - insylva-net
    restart: unless-stopped

  mongo:
    image: mongo:latest
    container_name: in-sylva.mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: in_sylva_mongoc
      MONGO_INITDB_ROOT_PASSWORD: v2kGBDUaGjXK2VuPyf5R64VS
      MONGO_INITDB_DATABASE: insylva
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - insylva-net
    restart: unless-stopped

  mongo-express:
    image: mongo-express
    ports:
      - 8881:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: in_sylva_mongoc
      ME_CONFIG_MONGODB_ADMINPASSWORD: v2kGBDUaGjXK2VuPyf5R64VS
    networks:
      - insylva-net
    restart: unless-stopped

  odfe-node1:
    image: amazon/opendistro-for-elasticsearch:latest
    container_name: odfe-node1
    environment:
      - cluster.name=odfe-cluster
      - node.name=odfe-node1
      - discovery.seed_hosts=odfe-node1,odfe-node2
      - cluster.initial_master_nodes=odfe-node1,odfe-node2
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
      - network.host=0.0.0.0
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the Elasticsearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - odfe-data1:/usr/share/elasticsearch/data
      - ./root-ca.pem:/usr/share/elasticsearch/config/root-ca.pem
      - ./node.pem:/usr/share/elasticsearch/config/node.pem
      - ./node-key.pem:/usr/share/elasticsearch/config/node-key.pem
      - ./admin.pem:/usr/share/elasticsearch/config/admin.pem
      - ./admin-key.pem:/usr/share/elasticsearch/config/admin-key.pem
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./internal_users.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/internal_users.yml
      - ./roles_mapping.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/roles_mapping.yml
      - ./tenants.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/tenants.yml
      - ./roles.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/roles.yml
      - ./action_groups.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/action_groups.yml
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer
    networks:
      - insylva-net
    restart: unless-stopped

  odfe-node2:
    image: amazon/opendistro-for-elasticsearch:latest
    container_name: odfe-node2
    environment:
      - cluster.name=odfe-cluster
      - node.name=odfe-node2
      - discovery.seed_hosts=odfe-node1,odfe-node2
      - cluster.initial_master_nodes=odfe-node1,odfe-node2
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - network.host=0.0.0.0
      # - discovery.zen.ping.unicast.hosts=odfe-node1
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - odfe-data2:/usr/share/elasticsearch/data
      - ./root-ca.pem:/usr/share/elasticsearch/config/root-ca.pem
      - ./node.pem:/usr/share/elasticsearch/config/node.pem
      - ./node-key.pem:/usr/share/elasticsearch/config/node-key.pem
      - ./admin.pem:/usr/share/elasticsearch/config/admin.pem
      - ./admin-key.pem:/usr/share/elasticsearch/config/admin-key.pem
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./internal_users.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/internal_users.yml
      - ./roles_mapping.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/roles_mapping.yml
      - ./tenants.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/tenants.yml
      - ./roles.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/roles.yml
      - ./action_groups.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/action_groups.yml
    networks:
      - insylva-net
    restart: unless-stopped

  kibana:
    image: amazon/opendistro-for-elasticsearch-kibana:latest
    container_name: odfe-kibana
    ports:
      - 5601:5601
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
      SERVER_HOST: 0.0.0.0
      ELASTICSEARCH_URL: http://odfe-node1:9200
      ELASTICSEARCH_HOSTS: http://odfe-node1:9200
    links: 
      - odfe-node1
      - odfe-node2
    networks:
      - insylva-net
    restart: unless-stopped
  
  search-api: 
    image: in-sylva.search.api:latest
    container_name: in-sylva.search.api
    ports: 
      - 9001:9001
    environment: 
      PORT: 9001
      network.host: 0.0.0.0
      NODE_ENV: production

      DB_HOST: in-sylva.postgres 
      DB_USERNAME: insylva_admin_pg 
      DB_PASSWORD: v2kGBDUaGjXK2VuPyf5R64VS 
      DB_DATABASE: insylva
      DB_PORT: 5432 

      ELK_HOST: odfe-node1
      ELK_PORT: 9200
      ELK_USERNAME: admin 
      ELK_PASSWORD: InSylva146544

      KEYCLOAK_REALM: in-sylva
      KEYCLOAK_SERVER_URL: http://localhost:7000/keycloak/auth
      KEYCLOAK_CLIENT_ID: in-sylva.user.app
    links: 
      - postgres
      - odfe-node1
      - keycloak
    networks:
      - insylva-net
    restart: unless-stopped

  gatekeeper:
    image: in-sylva.gatekeeper:latest
    container_name: in-sylva.gatekeeper
    ports:
      - 4000:4000
    environment:
      network.host: 0.0.0.0 
      PROCESS_TYPE: web 

      DB_HOST: in-sylva.postgres
      DB_PORT: 5432 
      DB_USER: insylva_admin_pg 
      DB_PASSWORD: v2kGBDUaGjXK2VuPyf5R64VS 
      DB_DATABASE: insylva 
      PORT: 4000

      IN_SYLVA_KEYCLOAK_HOST: http://in-sylva.keycloak
      IN_SYLVA_KEYCLOAK_PORT: 8080

      KEYCLOAK_USERNAME: insylva_admin
      KEYCLOAK_PASSWORD: v2kGBDUaGjXK2VuPyf5R64VS
      KEYCLOAK_GRANT_TYPE: password
      KEYCLOAK_CLIENT_ID: admin-cli

      KEYCLOAK_REALM: in-sylva
      KEYCLOAK_SERVER_URL: http://in-sylva.keycloak:8080/keycloak/auth
      KEYCLOAK_SERVER_PUBLIC_KEY: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAg4McMvQ2TP6GW0934XK8vceWjiE6IxVLwjSVdyshIIZ/wuqFKLWz0NhvIe22pG9wuddhcwQS0i5ZAy4HMJCXhVueGlqBVCu3ypc7cBogEB3osmpYK/qdWGb17UlVxrw2RujhaPWvioT5iKJOdrjTSKMCR/26oH1LOrNy1zzxTK3m4KNavx0iPt0Z1qYGv0WXJ00vTH4Nda3WDSwj+fioRCMqPwDkiwPFs6CCGOHt8L8GkLKIztXfLvfLsHIR4ua/wX5kJFjsndw+D40UV/xdMFg32Oim2vfvg3rSnXJs90yZ3xa8i5DzwhKFOTmSzDjSnJCk4Xtz1FmN5hapwUjQTwIDAQAB
      
    networks:
      - insylva-net

    restart: unless-stopped

  source-manager:
    image: in-sylva.source.manager:latest
    container_name: in-sylva.source.manager
    environment:
      network.host: 0.0.0.0
      PROCESS_TYPE: web 

      BOT_SERVICE_TOKEN: xoxb-791472305859-913372508932-2CcYhaCRrTLDXzKc5Df9ZMUb 
      BOT_SERVICE_CHANNEL: CPLTQQQ0Y 

      IN_SYLVA_GATEKEEPER_HOST: http://in-sylva.gatekeeper 
      IN_SYLVA_GATEKEEPER_PORT: 4000 

      MONGO_HOST: mongo 
      MONGO_USERNAME: in_sylva_mongoc 
      MONGO_PASSWORD: v2kGBDUaGjXK2VuPyf5R64VS 
      MONGO_DB_NAME: insylva 
      MONGO_PORT: 27017 

      DB_HOST: postgres 
      DB_USER: insylva_admin_pg 
      DB_PASSWORD: v2kGBDUaGjXK2VuPyf5R64VS 
      DB_DATABASE: insylva 
      DB_PORT: 5432 

      ELK_HOST: odfe-node1
      ELK_PORT: 9200
      ELK_USERNAME: admin
      ELK_PASSWORD: InSylva146544

      KEYCLOAK_REALM: in-sylva
      SERVER_URL: http://keycloak:8080/keycloak/auth
      CLIENT_ID: in-sylva.user.app

      PORT: 5000
    ports:
      - 5000:5000
    links: 
      - mongo
      - postgres
      - odfe-node1
      - keycloak
    networks:
      - insylva-net
    restart: unless-stopped

  portal:
    image: in-sylva.portal:latest
    container_name: in-sylva.portal
    ports:
      - 3000:3000
    links: 
      - gatekeeper
      - keycloak
      - source-manager
    networks:
      - insylva-net
    restart: unless-stopped
  
  login:
    image: in-sylva.user.login:latest
    container_name: in-sylva.user.login
    environment: 
      network.host: 0.0.0.0
      IN_SYLVA_GATEKEEPER_HOST: http://gatekeeper
      IN_SYLVA_GATEKEEPER_PORT: 4000
      IN_SYLVA_KEYCLOAK_HOST:  http://keycloak
      IN_SYLVA_KEYCLOAK_PORT: 8080
      IN_SYLVA_SEARCH_HOST: http://search
      IN_SYLVA_SEARCH_PORT: 3001
      IN_SYLVA_PORTAL_HOST: http://portal
      IN_SYLVA_PORTAL_PORT: 3000
      IN_SYLVA_CLIENT_ID: "in-sylva.user.app"
      IN_SYLVA_GRANT_TYPE: "password"
      IN_SYLVA_REALM: "in-sylva"
    ports:
     - 8080:8080
    links:  
      - gatekeeper
      - keycloak
      - search
      - portal
    networks:
      - insylva-net
    restart: unless-stopped

  search:
    image: in-sylva.search:latest
    container_name: in-sylva.search
    environment: 
      network.host: 0.0.0.0
      REACT_insylva_IN_SYLVA_GATEKEEPER_HOST: http://in-sylva.gatekeeper 
      REACT_insylva_IN_SYLVA_GATEKEEPER_PORT: 4000 
      REACT_insylva_IN_SYLVA_SOURCE_MANAGER_HOST: http://in-sylva.source.manager
      REACT_insylva_IN_SYLVA_SOURCE_MANAGER_PORT: 5000
      REACT_insylva_IN_SYLVA_KEYCLOAK_HOST: http://in-sylva.keycloak
      REACT_insylva_IN_SYLVA_KEYCLOAK_PORT: 7000
    ports:
      - 3001:3000
    networks:
      - insylva-net
    restart: unless-stopped

  portainer:
    container_name: in-sylva.portainer
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    restart: unless-stopped
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data   

  doc: 
    container_name: in-sylva.doc 
    image: in-sylva.doc:latest
    restart: unless-stopped
    volumes:
      - ./docs:/app/docs
      - ./doc/website/blog:/app/website/blog
      - ./doc/website/core:/app/website/core
      - ./doc/website/i18n:/app/website/i18n
      - ./doc/website/pages:/app/website/pages
    ports:
      - 3004:3000
      - 35729:35729

volumes:
  postgres-data:
  pgadmin:
  odfe-data1:
  odfe-data2:
  portainer_data:

networks:
  insylva-net:
    driver: bridge