window._env_ = {
  REACT_APP_IN_SYLVA_GATEKEEPER_HOST: "/gatekeeper",
  REACT_APP_IN_SYLVA_SOURCE_MANAGER_HOST: "/source-manager",
  REACT_APP_IN_SYLVA_KEYCLOAK_HOST: "/keycloak",
  REACT_APP_IN_SYLVA_CLIENT_ID: "in-sylva.user.app",
  REACT_APP_IN_SYLVA_GRANT_TYPE: "password",
  REACT_APP_IN_SYLVA_REALM: "in-sylva",
  REACT_APP_IN_SYLVA_LOGIN_HOST: "http://147.10.18.99",
  REACT_APP_IN_SYLVA_LOGIN_PORT: "8080",
  REACT_APP_PORT: "3000",
}
