FROM amazon/opendistro-for-elasticsearch:1.9.0


# COPY --chown=elasticsearch:elasticsearch config.yml /usr/share/elasticsearch/plugins/opendistro_security/securityconfig/config.yml
# COPY --chown=elasticsearch:elasticsearch custom-elasticsearch.yml /usr/share/elasticsearch/config/elasticsearch.yml
# COPY --chown=elasticsearch:elasticsearch node.pem /usr/share/elasticsearch/config/node.pem
# COPY --chown=elasticsearch:elasticsearch node-key.pem /usr/share/elasticsearch/config/node-key.pem
# COPY --chown=elasticsearch:elasticsearch admin.pem /usr/share/elasticsearch/config/admin.pem
# COPY --chown=elasticsearch:elasticsearch admin-key.pem /usr/share/elasticsearch/config/admin-key.pem
# COPY --chown=elasticsearch:elasticsearch root-ca.pem /usr/share/elasticsearch/config/root-ca.pem
